@ticketId = 605db6d6671d640018c96656
@orderId = 605db6e2a55220003bb0bcac

// Create Ticket
POST https://ticketing.dev/api/tickets
Content-Type: application/json

{
    "title":"concert",
    "price":10
}

###

// Update Ticket
PUT https://ticketing.dev/api/tickets/{{ticketId}}
Content-Type: application/json

{
    "title":"concert 3",
    "price":120
}

###

// Get Ticket by Id
GET https://ticketing.dev/api/tickets/{{ticketId}}
Content-Type: application/json

###

// Get Ticket List
GET https://ticketing.dev/api/tickets
Content-Type: application/json


###

// Create Order
POST https://ticketing.dev/api/orders
Content-Type: application/json

{
    "ticketId":"{{ticketId}}"
}

###

// Get Order by Id
Get https://ticketing.dev/api/orders/{{orderId}}
Content-Type: application/json