name: tests-payments

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && echo ${{secrets.STRIPE_KEY}} && npm install && npm run test:ci
        env:
          CI: true
          STRIPE_KEY: ${{secrets.STRIPE_KEY}}
